#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

CONF="turboacc"
PROG="/usr/share/turboacc/turboacc.uc"

service_triggers() {
    procd_add_reload_trigger "$CONF"
}

start_service() {
    $PROG start
}

stop_service() {
    $PROG stop
}

reload_service() {
    $PROG restart
}
