#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01

SERVER_NAME=AdGuardHome
CONFIGURATION=${SERVER_NAME}
ADG_HELPER="/usr/share/AdGuardHome/AdGuardHome.uc"

service_triggers() {
    procd_add_reload_trigger "${SERVER_NAME}"
}

start_service() {
    local raw=$($ADG_HELPER run | tr -d '\r' | sed 's/#$//' | xargs)

    if [ -z "$raw" ] || [ "$raw" = "false" ]; then
        logger -t ${SERVER_NAME} "Service disabled, cleaning up..."
        $ADG_HELPER stop
        return 0;
    else
        logger -t ${SERVER_NAME} "Starting with args: $raw"
        procd_open_instance "${SERVER_NAME}"
        procd_set_param file "/etc/config/${SERVER_NAME}"

        eval "set -- $raw"
        procd_set_param command "$@"

        procd_set_param respawn 3600 5 5
        procd_set_param stderr 1
        procd_set_param stdout 1
        procd_close_instance
    fi
}

stop_service() {
    $ADG_HELPER stop
}
