include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-poweroff

LUCI_TITLE:=LuCI support for poweroff
LUCI_DEPENDS:=
LUCI_DESCRIPTION:=LuCI support for poweroff


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature