#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01

SERVER_NAME=AdGuardHome
CONFIGURATION=AdGuardHome
ADG_HELPER="/usr/share/adguardhome/adguardhome.uc"

service_triggers() {
    procd_add_reload_trigger "AdGuardHome"
}

start_service() {
    local raw
    raw=$($ADG_HELPER apply | tr -d '\r' | sed 's/#$//' | xargs)
    
    logger -t AdGuardHome "Starting with args: $raw"

    procd_open_instance "AdGuardHome"
    procd_set_param file "/etc/config/AdGuardHome"

    if [ -n "$raw" ] && [ "$raw" != "false" ]; then
        local tz=$(cat /etc/TZ 2>/dev/null)
        [ -n "$tz" ] && procd_set_param env TZ="$tz"
        procd_set_param limits nofile="65535 65535"
        procd_set_param respawn 3600 5 5
        procd_set_param stderr 1
        
        eval "set -- $raw"
        procd_set_param command "$@" 
    else
        procd_set_param command /bin/true
    fi
    procd_close_instance
}

reload_service() {
    local enabled=$($ADG_HELPER reload) 

    if [ "$enabled" = "1" ]; then
        stop
        sleep 1
        start
    else
        stop
    fi
}

stop_service() {
    $ADG_HELPER stop
}
