include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for frpc

PKG_NAME:=luci-app-frpc
PKG_VERSION:=1.0
PKG_RELEASE:=3

LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
