include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-rtp2httpd
PKG_VERSION:=3.16.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for rtp2httpd
LUCI_DEPENDS:=+rtp2httpd

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
